# Generated by Codex on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_contract_invoice_ticket_productionrequest_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
