# Generated by Django 4.2.30 on 2026-07-28 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reference_doc',
            field=models.ForeignKey(blank=True, help_text="Harakat asosi bo'lgan hujjat (ixtiyoriy)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='api.document'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='target_warehouse',
            field=models.ForeignKey(blank=True, help_text="Faqat TRANSFER uchun: material ko'chiriladigan ombor", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='api.warehouse'),
        ),
    ]
