# Generated by Django 4.2.30 on 2026-08-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_stockmovement_reference_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('created', 'YARATILDI'), ('architecture', 'ARXITEKTURADA'), ('ceo', 'RAISDA'), ('procurement', 'XARIDLARDA'), ('anticorruption', 'NAZORATDA'), ('accountant', 'BUXGALTERIYADA'), ('delivering', 'YETKAZILMOQDA'), ('received', 'QABUL QILINDI'), ('closed', 'YOPILDI'), ('rejected', 'RAD ETILDI')], default='created', max_length=20),
        ),
    ]
