# Generated by Django 4.2.30 on 2026-08-06 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_migrate_workflow_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('created', 'YARATILDI'), ('revision', 'TUZATISHDA'), ('architecture', 'ARXITEKTURADA'), ('ceo', 'RAISDA'), ('procurement', 'XARIDLARDA'), ('anticorruption', 'NAZORATDA'), ('accountant', 'BUXGALTERIYADA'), ('delivering', 'YETKAZILMOQDA'), ('received', 'QABUL QILINDI'), ('closed', 'YOPILDI'), ('rejected', 'RAD ETILDI')], default='created', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_comments', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.document')),
            ],
            options={
                'db_table': 'document_comments',
                'ordering': ['created_at'],
            },
        ),
    ]
