# Generated by Django 4.2.30 on 2026-08-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_document_status_documentcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['id'], 'verbose_name': 'Manzil', 'verbose_name_plural': 'Manzillar'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['id'], 'verbose_name': 'Omborxona', 'verbose_name_plural': 'Omborxonalar'},
        ),
    ]
