# Generated by Django 4.2.30 on 2026-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_address_options_alter_warehouse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
