# Generated by Django 4.2.30 on 2026-08-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_backfill_notification_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentapproval',
            name='target_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
