import { Plus, Search, X } from "lucide-react";
import { useDeferredValue, useMemo, useState } from "react";
import { useCreatePurchaseOrder, usePurchaseOrders } from "../../hooks/usePurchaseOrders";
import type { PurchaseOrderCreatePayload } from "../../types/purchaseOrder";
import { PurchaseOrderCard } from "./PurchaseOrderCard";
import { PurchaseOrderForm } from "./PurchaseOrderForm";

export default function PurchasesPage() {
  const [query, setQuery] = useState("");
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const deferredQuery = useDeferredValue(query);
  const { data: purchaseOrders = [], isPending, isError } = usePurchaseOrders();
  const createPurchaseOrder = useCreatePurchaseOrder();
  const filteredPurchaseOrders = useMemo(() => { const normalizedQuery = deferredQuery.trim().toLocaleLowerCase(); return !normalizedQuery ? purchaseOrders : purchaseOrders.filter((purchaseOrder) => [purchaseOrder.title, purchaseOrder.doc_number, purchaseOrder.supplier_name ?? ""].some((value) => value.toLocaleLowerCase().includes(normalizedQuery))); }, [deferredQuery, purchaseOrders]);

  return <main className="min-h-full bg-gray-50 p-6"><div className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-gray-900">Xaridlar</h1><p className="mt-0.5 text-sm text-gray-400">{isPending ? "Yuklanmoqda..." : `${filteredPurchaseOrders.length} ta xarid`}</p></div><div className="flex flex-wrap items-center gap-2"><button type="button" onClick={() => setIsCreateOpen(true)} className="inline-flex items-center gap-1.5 rounded-xl bg-green-600 px-3 py-2 text-sm font-semibold text-white hover:bg-green-700"><Plus size={16} /> Xarid qo‘shish</button><label className="relative"><span className="sr-only">Xaridlarni qidirish</span><Search size={15} className="absolute top-1/2 left-3 -translate-y-1/2 text-gray-400" /><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Qidirish..." className="w-52 rounded-xl border border-gray-200 bg-white py-2 pr-3 pl-9 text-sm focus:border-green-500 focus:outline-none focus:ring-2 focus:ring-green-500/30" /></label></div></header>{isPending && <PageState>Yuklanmoqda...</PageState>}{isError && <PageState className="text-red-500">Xaridlarni yuklashda xatolik yuz berdi</PageState>}{!isPending && !isError && filteredPurchaseOrders.length === 0 && <PageState>Xaridlar topilmadi</PageState>}{!isPending && !isError && filteredPurchaseOrders.length > 0 && <section className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3" aria-label="Xaridlar ro‘yxati">{filteredPurchaseOrders.map((purchaseOrder) => <PurchaseOrderCard key={purchaseOrder.id} purchaseOrder={purchaseOrder} />)}</section>}</div>{isCreateOpen && <div role="dialog" aria-modal="true" aria-labelledby="create-purchase-order-title" className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><div className="mb-5 flex items-center justify-between gap-4"><div><h2 id="create-purchase-order-title" className="text-xl font-bold text-gray-900">Yangi xarid</h2><p className="mt-1 text-sm text-gray-500">Xarid ma’lumotlarini kiriting.</p></div><button type="button" aria-label="Yopish" onClick={() => setIsCreateOpen(false)} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><X size={18} /></button></div>{createPurchaseOrder.isError && <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-600">Xaridni yaratib bo‘lmadi. Ma’lumotlarni tekshirib, qayta urinib ko‘ring.</p>}<PurchaseOrderForm isSubmitting={createPurchaseOrder.isPending} onCancel={() => setIsCreateOpen(false)} onSubmit={(payload) => createPurchaseOrder.mutate(payload as PurchaseOrderCreatePayload, { onSuccess: () => setIsCreateOpen(false) })} /></div></div>}</main>;
}

function PageState({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`flex h-40 items-center justify-center text-sm text-gray-400 ${className}`}>{children}</div>; }
